### ISSUE TITLE
unbound ident error on HEAD Racket, FYI

### ISSUE THREAD

**Issue by pnwamk** [jsmaniac/phc-toolkit#4]
https://github.com/jsmaniac/phc-toolkit/blob/4694f870859cd33f46f493a70bb722ca05faa99f/untyped-only/syntax-parse.rkt#L61

I'm getting this error when trying to build the `phc` related packages on the latest builds of Racket:

```
pkgs/phc-toolkit/untyped-only/syntax-parse.rkt:61:14: -attribute-mapping-syntax?: reference to an unbound identifier
  at phase: 1; the transformer environment
  in: -attribute-mapping-syntax?
```

(I'm trying this on Racket commit f3644074ca108dd7397c5fa02dbc479fb0f12b5c, FYI)

**Comment by SuzanneSoy** [comment]
Thanks for the heads-up, Andrew!

I actually had a fix in my dev branch for a while, but it was blocked by https://github.com/racket/typed-racket/issues/688 . I got a bit mixed up in my branches, and didn't realize that that issue had been fixed for a while.

Fixed in c459bff, sorry for the delay !
